# -*- coding: utf-8 -*-
"""Matplot_test.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1wPZezGe3ttGCsVIcky8UP_IrKO9A-t19
"""

import matplotlib.pyplot as plt
import seaborn as sns
import pandas as pd
d=sns.load_dataset('healthexp')
d.head(5)

plt.figure(figsize=(5,4))
plt.bar(d.Country,d.Spending_USD)
plt.title("Bar Plot on Health Expenses")
plt.xlabel("Country")
plt.ylabel("Spending in USD")
plt.xticks(rotation=45);
plt.show()

import matplotlib.pyplot as plt
import seaborn as sns
import pandas as pd
pen=sns.load_dataset('penguins')
pen.head(5)

plt.figure(figsize=(5,4))
plt.scatter(pen.body_mass_g,pen.flipper_length_mm)
plt.title('Scatter plot')
plt.xlabel('flipper_mass_g')
plt.ylabel('flipper_length_mm')
plt.show()

plt.figure(figsize=(5,4))
plt.hist(pen.body_mass_g)
plt.title('Histogram plot')
plt.xlabel('body_mass_g')
plt.ylabel('Frequency')
plt.show()

pen.species

t=pen.species.value_counts()
t.values

t.index

plt.figure(figsize=(5,4))
plt.pie(t.values,labels=t.index,autopct='%.2f%%',explode=[0,0,0.2])
plt.title('Pie Chart')
plt.show()

plt.figure(figsize=(5,4))
plt.boxplot()